/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Wavelength = number;
export type Experimenttype = string;

export interface DataCollection {
  wavelength: Wavelength;
  DataCollectionGroup: DataCollectionGroup;
}
export interface DataCollectionGroup {
  experimentType: Experimenttype;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withDataCollection<TBase extends Constructor>(Base: TBase) {
  return class WithDataCollection extends Base {
    wavelength: Wavelength;
    DataCollectionGroup: DataCollectionGroup;
  }
}
export function withDataCollectionGroup<TBase extends Constructor>(Base: TBase) {
  return class WithDataCollectionGroup extends Base {
    experimentType: Experimenttype;
  }
}
