/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Wavelength = number;
export type Datacollectiongroupid = number;
export type Experimenttype = string;

export interface DataCollection {
  wavelength?: Wavelength;
  DataCollectionGroup: DataCollectionGroup;
  _metadata: DataCollectionMetaData;
}
export interface DataCollectionGroup {
  dataCollectionGroupId: Datacollectiongroupid;
  experimentType: Experimenttype;
}
export interface DataCollectionMetaData {
  snapshots: Snapshots;
}
/**
 * Snapshot statuses with ids 1-4
 */
export interface Snapshots {
  [k: string]: boolean;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withDataCollection<TBase extends Constructor>(Base: TBase) {
  return class WithDataCollection extends Base {
    wavelength?: Wavelength;
    DataCollectionGroup: DataCollectionGroup;
    _metadata: DataCollectionMetaData;
  };
}
export function withDataCollectionGroup<TBase extends Constructor>(
  Base: TBase
) {
  return class WithDataCollectionGroup extends Base {
    dataCollectionGroupId: Datacollectiongroupid;
    experimentType: Experimenttype;
  };
}
export function withDataCollectionMetaData<TBase extends Constructor>(
  Base: TBase
) {
  return class WithDataCollectionMetaData extends Base {
    snapshots: Snapshots;
  };
  /**
   * Snapshot statuses with ids 1-4
   */
}
export function withSnapshots<TBase extends Constructor>(Base: TBase) {
  return class WithSnapshots extends Base {
    [k: string]: boolean;
  };
}
