/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of datacollections
 */
export type Datacollections = number;
/**
 * UI groups for this session
 */
export type Uigroups = string[];
/**
 * Number of people registered on this session
 */
export type Persons = number;
/**
 * Whether this session is active
 */
export type Active = boolean;
/**
 * Whether this session is due to start soon or has ended recently (+/-20 min)
 */
export type ActiveSoon = boolean;

export interface SessionMetaData {
  datacollections?: Datacollections;
  uiGroups?: Uigroups;
  persons: Persons;
  active: Active;
  active_soon: ActiveSoon;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSessionMetaData<TBase extends Constructor>(Base: TBase) {
  return class WithSessionMetaData extends Base {
    datacollections?: Datacollections;
    uiGroups?: Uigroups;
    persons: Persons;
    active: Active;
    active_soon: ActiveSoon;
  };
}
