/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Acronym = string;
export type Description = string;
export type Hazardgroup = number;
export type Containmentlevel = number;
export type Safetylevel = string;
export type Molecularmass = number;
export type Proteintype = string;
export type Iscreatedbysamplesheet = number;
export type Sequence = string;
export type ModId = string;
export type Componenttypeid = number;
export type Concentrationtypeid = number;
export type Externalid = number;
export type Density = number;
export type Abundance = number;
export type Isotropy = string;
export type Siteid = number;
export type Personuuid = string;
export type Familyname = string;
export type Givenname = string;
export type Title = string;
export type Emailaddress = string;
export type Phonenumber = string;
export type Login = string;
export type Faxnumber = string;
export type Cache = string;
export type Externalid1 = number;
/**
 * The Laboratory name
 */
export type LaboratoryName = string;
/**
 * The Laboratory Address
 */
export type Address = string;
/**
 * The Laboratory City
 */
export type City = string;
/**
 * The Laboratory Country
 */
export type Country = string;
/**
 * The Laboratory optional URL
 */
export type URL = string;
/**
 * External Id from the User Portal
 */
export type LaboratoryExtPk = number;
/**
 * Time Laboratory was created
 */
export type RecordTimeStamp = string;

export interface UPProtein {
  name?: Name;
  acronym: Acronym;
  description?: Description;
  hazardGroup: Hazardgroup;
  containmentLevel: Containmentlevel;
  safetyLevel?: Safetylevel;
  molecularMass?: Molecularmass;
  proteinType?: Proteintype;
  isCreatedBySampleSheet?: Iscreatedbysamplesheet;
  sequence?: Sequence;
  MOD_ID?: ModId;
  componentTypeId?: Componenttypeid;
  concentrationTypeId?: Concentrationtypeid;
  externalId?: Externalid;
  density?: Density;
  abundance?: Abundance;
  isotropy?: Isotropy;
  person: PersonProposalLaboratory;
}
export interface PersonProposalLaboratory {
  siteId?: Siteid;
  personUUID?: Personuuid;
  familyName?: Familyname;
  givenName?: Givenname;
  title?: Title;
  emailAddress?: Emailaddress;
  phoneNumber?: Phonenumber;
  login?: Login;
  faxNumber?: Faxnumber;
  cache?: Cache;
  externalId?: Externalid1;
  laboratory?: LaboratoryCreate;
}
export interface LaboratoryCreate {
  name: LaboratoryName;
  address: Address;
  city: City;
  country: Country;
  url?: URL;
  laboratoryExtPk?: LaboratoryExtPk;
  recordTimeStamp?: RecordTimeStamp;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withUPProtein<TBase extends Constructor>(Base: TBase) {
  return class WithUPProtein extends Base {
    name?: Name;
    acronym: Acronym;
    description?: Description;
    hazardGroup: Hazardgroup;
    containmentLevel: Containmentlevel;
    safetyLevel?: Safetylevel;
    molecularMass?: Molecularmass;
    proteinType?: Proteintype;
    isCreatedBySampleSheet?: Iscreatedbysamplesheet;
    sequence?: Sequence;
    MOD_ID?: ModId;
    componentTypeId?: Componenttypeid;
    concentrationTypeId?: Concentrationtypeid;
    externalId?: Externalid;
    density?: Density;
    abundance?: Abundance;
    isotropy?: Isotropy;
    person: PersonProposalLaboratory;
  };
}
export function withPersonProposalLaboratory<TBase extends Constructor>(
  Base: TBase
) {
  return class WithPersonProposalLaboratory extends Base {
    siteId?: Siteid;
    personUUID?: Personuuid;
    familyName?: Familyname;
    givenName?: Givenname;
    title?: Title;
    emailAddress?: Emailaddress;
    phoneNumber?: Phonenumber;
    login?: Login;
    faxNumber?: Faxnumber;
    cache?: Cache;
    externalId?: Externalid1;
    laboratory?: LaboratoryCreate;
  };
}
export function withLaboratoryCreate<TBase extends Constructor>(Base: TBase) {
  return class WithLaboratoryCreate extends Base {
    name: LaboratoryName;
    address: Address;
    city: City;
    country: Country;
    url?: URL;
    laboratoryExtPk?: LaboratoryExtPk;
    recordTimeStamp?: RecordTimeStamp;
  };
}
